### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool error

### ISSUE THREAD

**Issue by martin0496** [luxonis/blobconverter#50]
**I tried to convert from openvino to xml but I keeo getting this error :** 
**What should be the cause of this requests.exceptions.SSLError: HTTPSConnectionPool error ?**

Downloading C:\Users\mahdi.mseddi\.cache\blobconverter\best_openvino_2021.4_4shave.blob...
Traceback (most recent call last):
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blobconverter.luxonis.com', port=443): Max retries exceeded with url: /compile?version=2021.4&no_cache=False (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\blobconverter\__main__.py", line 3, in <module>
    __run_cli__()
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\blobconverter\__init__.py", line 574, in __run_cli__
    return from_openvino(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\blobconverter\__init__.py", line 477, in from_openvino
    return compile_blob(blob_name=Path(xml_name).stem, req_data={"name": Path(xml_name).stem}, req_files=files, **kwargs)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\blobconverter\__init__.py", line 311, in compile_blob
    response = requests.post(
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mahdi.mseddi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='blobconverter.luxonis.com', port=443): Max retries exceeded with url: /compile?version=2021.4&no_cache=False (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

**Comment by Erol444** [comment]
Hi @martin0496 ,
Could you share the MRE (minimal repro example)?
Thanks, Erik

**Comment by martin0496** [comment]
Hi @Erol444 

I am trying to convert an onnx format model with these code lines. 
I am getting this error: 
![im](https://user-images.githubusercontent.com/56509387/227974941-b0eab326-29af-4728-b00c-0fd1164ca512.PNG)

**Comment by jc-9** [comment]
I am having the same issue. Is there any resolution?

**Comment by HonzaCuhel** [comment]
Hi @jc-9 and @martin0496 ,

@jc-9, could you please share with me your model (you can send it to me via email; my address is jan.cuhel@luxonis.com)? 

@martin0496, is the issue still ongoing for you?

Best,
Jan

**Comment by jc-9** [comment]
Hi @martin0496  - Seems like this is an intermittent issue, I just reran the script and it worked.

**Comment by HonzaCuhel** [comment]
That's great, glad to hear that. The issue was probably related to an expired security token, which I renewed just before you posted the message. I'll close the issue now, but in case the problem would rise again, please re-open this issue.

Best,
Jan
