### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by IlyaGasanPetrGY** [luxonis/blobconverter#58]
Good day! im trying to convert onnx model to IR representation and get this error!
i will glad to get feedback! 

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Resize): /model.13/Resize>':
/model.13/Resize_input_cast_0 node not found in graph cache
[ ERROR ]  Traceback (most recent call last):
  File "/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 394, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 147, in moc_pipeline
    ngraph_function = moc_front_end.convert(input_model)
RuntimeError: While validating ONNX node '<Node(Resize): /model.13/Resize>':
/model.13/Resize_input_cast_0 node not found in graph cache

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by Erol444** [comment]
@IlyaGasanPetrGY I'd suggest opening an issue at [OpenVINO repo](https://github.com/openvinotoolkit/openvino) - blobconverter is just a wrapper around OpenVINO tools.

**Comment by IlyaGasanPetrGY** [comment]
You're very welcome for the quick response! I've already figured out the mistake. I'm sorry for bothering you
